// Generated by gencpp from file brginner_tutorials/AddTwoInts.msg
// DO NOT EDIT!


#ifndef BRGINNER_TUTORIALS_MESSAGE_ADDTWOINTS_H
#define BRGINNER_TUTORIALS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <brginner_tutorials/AddTwoIntsRequest.h>
#include <brginner_tutorials/AddTwoIntsResponse.h>


namespace brginner_tutorials
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace brginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::brginner_tutorials::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::brginner_tutorials::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::brginner_tutorials::AddTwoInts > {
  static const char* value()
  {
    return "brginner_tutorials/AddTwoInts";
  }

  static const char* value(const ::brginner_tutorials::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::brginner_tutorials::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::brginner_tutorials::AddTwoInts >
template<>
struct MD5Sum< ::brginner_tutorials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::brginner_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::brginner_tutorials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::brginner_tutorials::AddTwoIntsRequest> should match
// service_traits::DataType< ::brginner_tutorials::AddTwoInts >
template<>
struct DataType< ::brginner_tutorials::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::brginner_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::brginner_tutorials::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::brginner_tutorials::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::brginner_tutorials::AddTwoInts >
template<>
struct MD5Sum< ::brginner_tutorials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::brginner_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::brginner_tutorials::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::brginner_tutorials::AddTwoIntsResponse> should match
// service_traits::DataType< ::brginner_tutorials::AddTwoInts >
template<>
struct DataType< ::brginner_tutorials::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::brginner_tutorials::AddTwoInts >::value();
  }
  static const char* value(const ::brginner_tutorials::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BRGINNER_TUTORIALS_MESSAGE_ADDTWOINTS_H
